"""testing mig

Revision ID: 17ee973d6a44
Revises: 17f430d66c73
Create Date: 2024-01-27 11:36:29.558115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ee973d6a44'
down_revision: Union[str, None] = '17f430d66c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testing')
    # ### end Alembic commands ###
