"""testing6

Revision ID: 3ca2b6b7d83c
Revises: 6e4db5d6a26e
Create Date: 2024-01-27 12:01:53.414428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca2b6b7d83c'
down_revision: Union[str, None] = '6e4db5d6a26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testing', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
