"""testing9

Revision ID: c9ba0998ed62
Revises: 106e5c792944
Create Date: 2024-01-27 12:58:14.844188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ba0998ed62'
down_revision: Union[str, None] = '106e5c792944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testing', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
